name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          load: true
      -
        name: Build and test frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          load: true
      -
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.event.repository.name }}-latest
      -
        name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.event.repository.name }}-latest
